# Generated by Django 2.1 on 2020-01-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=40)),
            ],
        ),
    ]
